// AUTO-GENERATED by the localization pipeline. Do not edit by hand.
import jaJP from "./ja-JP";
import koKR from "./ko-KR";
import zhTW from "./zh-TW";
import frFR from "./fr-FR";
import deDE from "./de-DE";
import esES from "./es-ES";
import ptBR from "./pt-BR";
import ruRU from "./ru-RU";
import itIT from "./it-IT";
import nlNL from "./nl-NL";
import trTR from "./tr-TR";
import plPL from "./pl-PL";
import viVN from "./vi-VN";
import thTH from "./th-TH";
import idID from "./id-ID";
import arEG from "./ar-EG";
import csCZ from "./cs-CZ";
import heIL from "./he-IL";
import hiIN from "./hi-IN";
import svSE from "./sv-SE";
import ukUA from "./uk-UA";

export const additionalTranslations: Record<string, Record<string, string>> = {
  "ja-JP": jaJP,
  "ko-KR": koKR,
  "zh-TW": zhTW,
  "fr-FR": frFR,
  "de-DE": deDE,
  "es-ES": esES,
  "pt-BR": ptBR,
  "ru-RU": ruRU,
  "it-IT": itIT,
  "nl-NL": nlNL,
  "tr-TR": trTR,
  "pl-PL": plPL,
  "vi-VN": viVN,
  "th-TH": thTH,
  "id-ID": idID,
  "ar-EG": arEG,
  "cs-CZ": csCZ,
  "he-IL": heIL,
  "hi-IN": hiIN,
  "sv-SE": svSE,
  "uk-UA": ukUA,
};
