// AUTO-GENERATED by the localization pipeline. Do not edit by hand.
import { starter as jaJP_starter } from "./ja-JP";
import { starter as koKR_starter } from "./ko-KR";
import { starter as zhTW_starter } from "./zh-TW";
import { starter as frFR_starter } from "./fr-FR";
import { starter as deDE_starter } from "./de-DE";
import { starter as esES_starter } from "./es-ES";
import { starter as ptBR_starter } from "./pt-BR";
import { starter as ruRU_starter } from "./ru-RU";
import { starter as itIT_starter } from "./it-IT";
import { starter as nlNL_starter } from "./nl-NL";
import { starter as trTR_starter } from "./tr-TR";
import { starter as plPL_starter } from "./pl-PL";
import { starter as viVN_starter } from "./vi-VN";
import { starter as thTH_starter } from "./th-TH";
import { starter as idID_starter } from "./id-ID";
import { starter as arEG_starter } from "./ar-EG";
import { starter as csCZ_starter } from "./cs-CZ";
import { starter as heIL_starter } from "./he-IL";
import { starter as hiIN_starter } from "./hi-IN";
import { starter as svSE_starter } from "./sv-SE";
import { starter as ukUA_starter } from "./uk-UA";
import { stockcount as jaJP_stockcount } from "./stockcount/ja-JP";
import { stockcount as koKR_stockcount } from "./stockcount/ko-KR";
import { stockcount as zhTW_stockcount } from "./stockcount/zh-TW";
import { stockcount as frFR_stockcount } from "./stockcount/fr-FR";
import { stockcount as deDE_stockcount } from "./stockcount/de-DE";
import { stockcount as esES_stockcount } from "./stockcount/es-ES";
import { stockcount as ptBR_stockcount } from "./stockcount/pt-BR";
import { stockcount as ruRU_stockcount } from "./stockcount/ru-RU";
import { stockcount as itIT_stockcount } from "./stockcount/it-IT";
import { stockcount as nlNL_stockcount } from "./stockcount/nl-NL";
import { stockcount as trTR_stockcount } from "./stockcount/tr-TR";
import { stockcount as plPL_stockcount } from "./stockcount/pl-PL";
import { stockcount as viVN_stockcount } from "./stockcount/vi-VN";
import { stockcount as thTH_stockcount } from "./stockcount/th-TH";
import { stockcount as idID_stockcount } from "./stockcount/id-ID";
import { stockcount as arEG_stockcount } from "./stockcount/ar-EG";
import { stockcount as csCZ_stockcount } from "./stockcount/cs-CZ";
import { stockcount as heIL_stockcount } from "./stockcount/he-IL";
import { stockcount as hiIN_stockcount } from "./stockcount/hi-IN";
import { stockcount as svSE_stockcount } from "./stockcount/sv-SE";
import { stockcount as ukUA_stockcount } from "./stockcount/uk-UA";

export const additionalTranslations: Record<string, Record<string, Record<string, string>>> = {
  "starter": {
    "ja-JP": jaJP_starter,
    "ko-KR": koKR_starter,
    "zh-TW": zhTW_starter,
    "fr-FR": frFR_starter,
    "de-DE": deDE_starter,
    "es-ES": esES_starter,
    "pt-BR": ptBR_starter,
    "ru-RU": ruRU_starter,
    "it-IT": itIT_starter,
    "nl-NL": nlNL_starter,
    "tr-TR": trTR_starter,
    "pl-PL": plPL_starter,
    "vi-VN": viVN_starter,
    "th-TH": thTH_starter,
    "id-ID": idID_starter,
    "ar-EG": arEG_starter,
    "cs-CZ": csCZ_starter,
    "he-IL": heIL_starter,
    "hi-IN": hiIN_starter,
    "sv-SE": svSE_starter,
    "uk-UA": ukUA_starter,
  },
  "stockcount": {
    "ja-JP": jaJP_stockcount,
    "ko-KR": koKR_stockcount,
    "zh-TW": zhTW_stockcount,
    "fr-FR": frFR_stockcount,
    "de-DE": deDE_stockcount,
    "es-ES": esES_stockcount,
    "pt-BR": ptBR_stockcount,
    "ru-RU": ruRU_stockcount,
    "it-IT": itIT_stockcount,
    "nl-NL": nlNL_stockcount,
    "tr-TR": trTR_stockcount,
    "pl-PL": plPL_stockcount,
    "vi-VN": viVN_stockcount,
    "th-TH": thTH_stockcount,
    "id-ID": idID_stockcount,
    "ar-EG": arEG_stockcount,
    "cs-CZ": csCZ_stockcount,
    "he-IL": heIL_stockcount,
    "hi-IN": hiIN_stockcount,
    "sv-SE": svSE_stockcount,
    "uk-UA": ukUA_stockcount,
  },
};
